### ISSUE TITLE
arduino code

### ISSUE THREAD

**Issue by vjdobermann** [WorldFamousElectronics/PulseSensor_Mac_App#2]
Hi,
the arduino code is unvailable, link dead.
could you post the code or repair the link please ?

Thanks in advance ;)

**Comment by biomurph** [comment]
Which link are you referring to?

**Comment by vjdobermann** [comment]
on the code tab at 1. Installation, on the top of the Arduino IDE screen capture

**Comment by joelSensor** [comment]
It was a typo in the url. Got it fixed.
